"""Emit data/incidents.json with the Phase 2.3 distribution.

INC-0001..0012 have hand-written field prose. The rest are templated but
varied enough to look like supervisor WhatsApp messages.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "incidents.json"


def inc(
    incident_id,
    site_id,
    hours_ago,
    report_delay_hours,
    reported_by,
    channel,
    raw_text,
    fatality=False,
    hospitalised=False,
    days_lost=0,
    persons=1,
    hazard_tags=None,
    control_present=False,
    near_miss=False,
    bucket="",
):
    return {
        "incident_id": incident_id,
        "site_id": site_id,
        "hours_ago": hours_ago,
        "report_delay_hours": report_delay_hours,
        "reported_by": reported_by,
        "channel": channel,
        "raw_text": raw_text,
        "media": [],
        "outcome": {
            "fatality": fatality,
            "hospitalised": hospitalised,
            "days_lost_estimate": days_lost,
            "persons_affected": persons,
        },
        "hazard_tags": hazard_tags or [],
        "control_present": control_present,
        "near_miss": near_miss,
        "bucket": bucket,
    }


INCIDENTS = [
    # --- 6 clearly reportable factory ---
    inc(
        "INC-0001",
        "S-BAD-02",
        6,
        2,
        "supervisor",
        "whatsapp_voice",
        "Around 2:40pm at Badlapur Unit 2, a helper's left hand was caught in the unguarded nip point of the conveyor drive during belt cleaning. He was taken to Sai Hospital, admitted, three fingers crushed. Machine was running. Supervisor stopped the line after.",
        hospitalised=True,
        days_lost=30,
        hazard_tags=["conveyor_nip_point", "guard_missing", "cleaning_while_running"],
        bucket="reportable_factory",
    ),
    inc(
        "INC-0002",
        "S-PUN-03",
        18,
        1,
        "shift_incharge",
        "whatsapp_text",
        "Press shop line 4. Operator's right index finger amputated at the first joint on the 250T press. Dual palm button was bypassed with a wooden block. Taken to Ruby Hall, admitted, surgery tonight.",
        hospitalised=True,
        days_lost=45,
        hazard_tags=["press_shop", "guard_bypass", "amputation"],
        bucket="reportable_factory",
    ),
    inc(
        "INC-0003",
        "S-NGP-01",
        30,
        3,
        "supervisor",
        "phone",
        "Molten metal splash from ladle on furnace 2. Helper got burns on both legs, more than 20 percent BSA. Admitted to Orange City Hospital ICU. Will not work for weeks.",
        hospitalised=True,
        days_lost=40,
        hazard_tags=["molten_metal", "ppe_gap", "heat_stress"],
        bucket="reportable_factory",
    ),
    inc(
        "INC-0004",
        "S-NSK-01",
        9,
        1,
        "ehs_officer",
        "app",
        "Painter collapsed in spray booth after solvent exposure. Confined space permit not taken. Hospitalised at Wockhardt, still on oxygen. Doctor said minimum 4 days off.",
        hospitalised=True,
        days_lost=5,
        hazard_tags=["solvent_vapour", "confined_space", "permit_missing"],
        bucket="reportable_factory",
    ),
    inc(
        "INC-0005",
        "S-AUR-01",
        40,
        4,
        "supervisor",
        "whatsapp_text",
        "Hammer man on forging hammer 3, flying scale hit left eye. Globe ruptured. Admitted, will lose the eye. Safety glasses were in the cabin not on his face.",
        hospitalised=True,
        days_lost=21,
        hazard_tags=["flying_scale", "eye_injury", "ppe_gap"],
        bucket="reportable_factory",
    ),
    inc(
        "INC-0006",
        "S-MUM-WH1",
        22,
        2,
        "warehouse_incharge",
        "email",
        "Forklift reversing in aisle B crushed a picker against racking. Pelvis fracture, admitted to Lilavati. Reverse beeper not working, spotter not posted.",
        hospitalised=True,
        days_lost=35,
        hazard_tags=["forklift", "pedestrian_interface", "no_spotter"],
        bucket="reportable_factory",
    ),
    # --- 5 clearly reportable construction ---
    inc(
        "INC-0007",
        "S-THN-CS1",
        5,
        1,
        "site_engineer",
        "whatsapp_voice",
        "Scaffold at pier P-12, fitter fell from 6m while tying reinforcement. Midrail missing on that bay. Taken to Jupiter Hospital Thane, femur fracture, admitted. Will be off more than a week.",
        hospitalised=True,
        days_lost=28,
        hazard_tags=["work_at_height", "scaffold_gap", "fall"],
        bucket="reportable_construction",
    ),
    inc(
        "INC-0008",
        "S-MUM-CS2",
        14,
        2,
        "safety_officer",
        "app",
        "Tower crane L2, slinger's hand crushed between load and column while landing a beam. Three metacarpals fractured. Hospitalised at Hinduja. Banksman not in position.",
        hospitalised=True,
        days_lost=20,
        hazard_tags=["lifting_operations", "crush", "banksman_missing"],
        bucket="reportable_construction",
    ),
    inc(
        "INC-0009",
        "S-PUN-CS3",
        8,
        1,
        "foreman",
        "whatsapp_text",
        "Excavation for pile cap near span 8 collapsed on two labourers. One has chest injury and is on ventilator at Ruby Hall. Shoring was not in. Depth was 3.2m.",
        hospitalised=True,
        days_lost=30,
        persons=2,
        hazard_tags=["excavation", "collapse", "shoring_missing"],
        bucket="reportable_construction",
    ),
    inc(
        "INC-0010",
        "S-NAV-CS4",
        11,
        2,
        "supervisor",
        "phone",
        "Confined space in tank T-04. Helper lost consciousness during grinding. Hot work permit expired yesterday. Admitted, suspected CO. Not returning this week.",
        hospitalised=True,
        days_lost=7,
        hazard_tags=["confined_space", "hot_work", "permit_expired"],
        bucket="reportable_construction",
    ),
    inc(
        "INC-0011",
        "S-NGP-CS5",
        26,
        3,
        "site_engineer",
        "whatsapp_text",
        "Dumper reversing on NH package hit a flagman. Compound fracture of tibia. Admitted to Wockhardt Nagpur. No banksman, reverse alarm dead.",
        hospitalised=True,
        days_lost=25,
        hazard_tags=["traffic_interface", "reversing", "no_spotter"],
        bucket="reportable_construction",
    ),
    # --- 2 fatalities ---
    inc(
        "INC-0012",
        "S-BAD-02",
        4,
        0.5,
        "plant_head",
        "phone",
        "Fatal at Badlapur Unit 2. Contractor electrician came in contact with 440V panel during live work. No LOTO. Declared dead at Sai Hospital 3:10pm. Family informed. DISH not yet notified.",
        fatality=True,
        hospitalised=True,
        days_lost=0,
        hazard_tags=["electrical", "lockout_tagout", "live_work"],
        bucket="fatality",
    ),
    inc(
        "INC-0013",
        "S-MUM-CS2",
        7,
        0.4,
        "project_manager",
        "phone",
        "Fatal fall from 18th floor slab at BKC Tower. Edge protection removed for concrete pour and not reinstated. Worker was tying shuttering. Police on site. Name withheld pending family.",
        fatality=True,
        hospitalised=False,
        days_lost=0,
        hazard_tags=["work_at_height", "edge_protection_missing", "fall"],
        bucket="fatality",
    ),
    # --- 10 near-miss, not reportable ---
    inc(
        "INC-0014",
        "S-PUN-03",
        48,
        1,
        "operator",
        "app",
        "Near miss. A spanner dropped from mezzanine in assembly. Nobody hit. Tool lanyard was not used. No injury.",
        near_miss=True,
        hazard_tags=["dropped_object", "work_at_height"],
        control_present=False,
        bucket="near_miss",
    ),
    inc(
        "INC-0015",
        "S-NSK-01",
        55,
        2,
        "painter",
        "whatsapp_text",
        "Almost slipped on wet floor near booth 2 after washdown. Caught the railing. No injury. Housekeeping delayed.",
        near_miss=True,
        hazard_tags=["slip", "wet_floor"],
        bucket="near_miss",
    ),
    inc(
        "INC-0016",
        "S-NGP-01",
        60,
        1,
        "crane_operator",
        "app",
        "Crane limit switch tripped while lifting a mould. Load did not drop. No one under the load. Near miss only.",
        near_miss=True,
        hazard_tags=["crane", "limit_switch"],
        control_present=True,
        bucket="near_miss",
    ),
    inc(
        "INC-0017",
        "S-MUM-WH1",
        70,
        1,
        "picker",
        "app",
        "Pallet shifted on rack L3 when forklift turned. Nothing fell. No injury. We restacked.",
        near_miss=True,
        hazard_tags=["rack_collapse", "forklift"],
        bucket="near_miss",
    ),
    inc(
        "INC-0018",
        "S-THN-CS1",
        36,
        1,
        "fitter",
        "whatsapp_text",
        "Rebar bundle slipped in sling by 20cm. Nobody under it. Tag line was on. No injury.",
        near_miss=True,
        hazard_tags=["lifting_operations"],
        control_present=True,
        bucket="near_miss",
    ),
    inc(
        "INC-0019",
        "S-PUN-CS3",
        80,
        2,
        "supervisor",
        "app",
        "Excavator swing almost hit a surveyor who walked into the exclusion zone. We stopped work. No contact, no injury.",
        near_miss=True,
        hazard_tags=["plant_interface", "exclusion_zone"],
        bucket="near_miss",
    ),
    inc(
        "INC-0020",
        "S-NAV-CS4",
        44,
        1,
        "welder",
        "app",
        "Flash from welding in pipe rack. Helper looked away in time. No burn. Screens were not up.",
        near_miss=True,
        hazard_tags=["hot_work", "arc_flash"],
        bucket="near_miss",
    ),
    inc(
        "INC-0021",
        "S-NGP-CS5",
        90,
        1,
        "flagman",
        "whatsapp_text",
        "Car came too close to the cone line. No one hit. We reset cones. Near miss with public traffic.",
        near_miss=True,
        hazard_tags=["traffic_interface"],
        bucket="near_miss",
    ),
    inc(
        "INC-0022",
        "S-AUR-01",
        100,
        2,
        "fitter",
        "app",
        "Oil leak on shop floor, one person slipped but held the machine. No fall, no injury. Maintenance wiped it.",
        near_miss=True,
        hazard_tags=["slip", "oil_spill"],
        bucket="near_miss",
    ),
    inc(
        "INC-0023",
        "S-KLY-01",
        110,
        1,
        "operator",
        "app",
        "E-stop used when a visitor walked toward a running line. Line stopped. No contact. Visitor induction incomplete.",
        near_miss=True,
        hazard_tags=["pedestrian_interface"],
        control_present=True,
        bucket="near_miss",
    ),
    # --- 6 near-miss SAME HAZARD as INC-0001 (conveyor_nip_point + guard_missing) ---
    inc(
        "INC-0024",
        "S-KLY-01",
        72,
        1,
        "operator",
        "whatsapp_text",
        "Near miss on packing conveyor. I was cleaning the belt, my glove almost went into the unguarded nip at the tail pulley. Machine was still running. Guard has been missing since last week. No injury this time.",
        near_miss=True,
        hazard_tags=["conveyor_nip_point", "guard_missing", "cleaning_while_running"],
        bucket="same_hazard_nearmiss",
    ),
    inc(
        "INC-0025",
        "S-AUR-01",
        96,
        2,
        "helper",
        "whatsapp_voice",
        "Forging shop transfer conveyor, same story. Guard on drive is off for maintenance and not put back. My sleeve caught for a second then tore. No injury. Please fix before someone loses a hand.",
        near_miss=True,
        hazard_tags=["conveyor_nip_point", "guard_missing"],
        bucket="same_hazard_nearmiss",
    ),
    inc(
        "INC-0026",
        "S-PUN-03",
        120,
        1,
        "supervisor",
        "app",
        "Assembly takeaway conveyor nip point exposed. Intern reached to remove a jammed carton. Pulled hand back. No injury. Guard bolts are missing.",
        near_miss=True,
        hazard_tags=["conveyor_nip_point", "guard_missing"],
        bucket="same_hazard_nearmiss",
    ),
    inc(
        "INC-0027",
        "S-MUM-WH1",
        50,
        1,
        "picker",
        "app",
        "Inbound belt conveyor, in-running nip not guarded after last belt change. Carton got pulled in. Nobody hurt. Same unguarded conveyor issue we keep logging.",
        near_miss=True,
        hazard_tags=["conveyor_nip_point", "guard_missing"],
        bucket="same_hazard_nearmiss",
    ),
    inc(
        "INC-0028",
        "S-NSK-01",
        140,
        2,
        "technician",
        "whatsapp_text",
        "Paint line overhead conveyor, chain guard left open. I was greasing, almost pinched. No injury. Guard_missing again.",
        near_miss=True,
        hazard_tags=["conveyor_nip_point", "guard_missing"],
        bucket="same_hazard_nearmiss",
    ),
    inc(
        "INC-0029",
        "S-NGP-01",
        160,
        1,
        "helper",
        "phone",
        "Sand plant conveyor, tail drum unguarded. Spade nearly pulled from my hand while cleaning. No injury. This is the same nip point problem as other plants.",
        near_miss=True,
        hazard_tags=["conveyor_nip_point", "guard_missing", "cleaning_while_running"],
        bucket="same_hazard_nearmiss",
    ),
    # --- 5 ambiguous (48-hour threshold) ---
    inc(
        "INC-0030",
        "S-KLY-01",
        10,
        3,
        "supervisor",
        "whatsapp_text",
        "Helper twisted ankle on packing floor after a carton fell. Went to the occupational health centre. Doctor put crepe bandage and sent him home. He says he will try light duty tomorrow. Not sure if he will miss 48 hours. No hospital admission.",
        hospitalised=False,
        days_lost=1,
        hazard_tags=["manual_handling", "slip"],
        bucket="ambiguous",
    ),
    inc(
        "INC-0031",
        "S-THN-CS1",
        12,
        2,
        "site_engineer",
        "whatsapp_voice",
        "Labourer cut his forearm on rebar. Site first aid, 6 stitches at a nearby clinic, came back to site in the afternoon sitting in the cabin. He might work tomorrow, might not. Not admitted overnight. Is this 48 hours or not? Nobody knows yet.",
        hospitalised=False,
        days_lost=1,
        hazard_tags=["work_at_height", "cut"],
        bucket="ambiguous",
    ),
    inc(
        "INC-0032",
        "S-PUN-03",
        16,
        4,
        "hr",
        "email",
        "Operator complained of back pain after lifting a fixture. OHC gave painkiller. He left early. Attendance for next two days is unknown. No fracture on the note. Is this reportable under s.88? Duration of incapacity not confirmed.",
        hospitalised=False,
        days_lost=2,
        hazard_tags=["manual_handling"],
        bucket="ambiguous",
    ),
    inc(
        "INC-0033",
        "S-NAV-CS4",
        20,
        5,
        "supervisor",
        "phone",
        "Welder got a flash. Eyes watering, went to city clinic, not admitted. Doctor said rest 24 to 72 hours depending on how he feels. We do not have a medical certificate yet. Could be under 48 hours, could be over.",
        hospitalised=False,
        days_lost=2,
        hazard_tags=["hot_work", "eye_injury"],
        bucket="ambiguous",
    ),
    inc(
        "INC-0034",
        "S-AUR-01",
        15,
        2,
        "supervisor",
        "app",
        "Finger jammed in a die, X-ray at local clinic, no fracture according to the tech but swelling is bad. He is at home. Occupier asked if we file Form 24 now or wait to see if he misses two days.",
        hospitalised=False,
        days_lost=2,
        hazard_tags=["press_shop"],
        bucket="ambiguous",
    ),
    # --- 3 dangerous occurrence, no injury ---
    inc(
        "INC-0035",
        "S-NSK-01",
        3,
        1,
        "shift_incharge",
        "phone",
        "Fire in paint shop solvent store. Sprinkler knocked it down in two minutes. Nobody injured, nobody admitted. Store door was left open. Whole bay evacuated.",
        near_miss=False,
        hazard_tags=["fire", "chemical_storage", "solvent_vapour"],
        bucket="dangerous_occurrence",
    ),
    inc(
        "INC-0036",
        "S-NGP-01",
        28,
        1,
        "plant_head",
        "email",
        "Cupola spark box explosion during light-up. No injury. Roof sheet blown. This is a dangerous occurrence even though nobody was hurt.",
        hazard_tags=["explosion", "molten_metal"],
        bucket="dangerous_occurrence",
    ),
    inc(
        "INC-0037",
        "S-PUN-03",
        33,
        2,
        "maintenance",
        "app",
        "Mezzanine walkway partial collapse during weekend. Area was empty. No injury. Structural crack. Building part collapse.",
        hazard_tags=["collapse_of_building"],
        bucket="dangerous_occurrence",
    ),
    # --- 2 occupational disease ---
    inc(
        "INC-0038",
        "S-NGP-01",
        50,
        8,
        "occupational_health",
        "email",
        "Foundry fettler diagnosed with silicosis after periodic medical. Chest X-ray and spirometry attached. He is still coming to work on advice of the doctor pending further tests. Third Schedule disease.",
        hospitalised=False,
        days_lost=0,
        hazard_tags=["silica_dust", "occupational_disease"],
        bucket="occupational_disease",
    ),
    inc(
        "INC-0039",
        "S-THN-CS1",
        60,
        10,
        "occupational_health",
        "email",
        "Concrete crew member noise-induced hearing loss confirmed on audiometry. Not an accident. Occupational disease notification path. He continues on site with PPE.",
        near_miss=False,
        hazard_tags=["noise", "occupational_disease"],
        bucket="occupational_disease",
    ),
    # --- 1 garbled / incomplete ---
    inc(
        "INC-0040",
        "S-PUN-CS3",
        2,
        0.2,
        "unknown",
        "whatsapp_voice",
        "sir pls come fast something happened near span 4 guy is down not sure if he fell or machine... hospital maybe... will msg later battery dying",
        hospitalised=False,
        days_lost=0,
        hazard_tags=[],
        bucket="garbled",
    ),
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(INCIDENTS, indent=2), encoding="utf-8")
    buckets: dict[str, int] = {}
    for row in INCIDENTS:
        buckets[row["bucket"]] = buckets.get(row["bucket"], 0) + 1
    print(f"wrote {len(INCIDENTS)} incidents -> {OUT}")
    print(buckets)


if __name__ == "__main__":
    main()
